### ISSUE TITLE
failed when run on android

### ISSUE THREAD

**Issue by dreambo8563** [NativeScript/sample-ng-http#1]
node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661: Cannot re-export name that is not defined in the module.

I download the code, and try to compile the mobile one, after tns run android, I got the fail

**Comment by hdeshev** [comment]
That's a known conflict with TypeScript 1.8 and Angular beta-6. Just pushed an update to this sample that uses beta-7 and fixes the problem.
